-- FUNÇÕES INSERT

CREATE OR REPLACE FUNCTION INSERIR_PAC(
    CPF TEXT,
    NOME TEXT,
    CONTATO TEXT,
    ENDERECO TEXT
) RETURNS VOID AS $$
BEGIN
    INSERT INTO PACIENTE (CPF, NOME, CONTATO, ENDERECO)
    VALUES (CPF, NOME, CONTATO, ENDERECO);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_MEDICAMENTO(
    NOME TEXT,
    BULA TEXT
) RETURNS VOID AS $$
BEGIN
    INSERT INTO MEDICAMENTO (NOME, BULA)
    VALUES (NOME, BULA);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_ITEM_MED(
    COD_CONS_INTER INT,
    COD_MED INT,
    QUANTIDADE INT,
	CONS_OU_INTER VARCHAR(1)
) RETURNS VOID AS $$
BEGIN
    INSERT INTO ITEM_MED (COD_CONS_INTER, COD_MED, QUANTIDADE, CONS_OU_INTER)
    VALUES (COD_CONS_INTER, COD_MED, QUANTIDADE, CONS_OU_INTER);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_FUNC(
    NOME TEXT,
    CPF TEXT
) RETURNS VOID AS $$
BEGIN
    INSERT INTO FUNCIONARIO (NOME, CPF)
    VALUES (NOME, CPF);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_CONSULTA(
    COD_PAC INT,
    CRM INT,
    COD_PLANO INT,
    MOTIVO TEXT,
    DT_PREV_CONSULTA DATE,
	STATUS VARCHAR(1)
) RETURNS VOID AS $$
BEGIN
    INSERT INTO CONSULTA (COD_PAC, CRM, COD_PLANO, MOTIVO, DT_PREV_CONSULTA, STATUS)
    VALUES (COD_PAC, CRM, COD_PLANO, MOTIVO, DT_PREV_CONSULTA, STATUS);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_PROC(
    COD_FUNC INT,
    COD_SERVICO INT,
    COD_PAC INT,
    DT_ATEND DATE,
    VALOR NUMERIC
) RETURNS VOID AS $$
BEGIN
    INSERT INTO PROCEDIMENTO (COD_FUNC, COD_SERVICO, COD_PAC, DT_ATEND, VALOR)
    VALUES (COD_FUNC, COD_SERVICO, COD_PAC, DT_ATEND, VALOR);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_PLANO(
    NOME TEXT,
    VALOR_CON NUMERIC,
    VALOR_INT NUMERIC
) RETURNS VOID AS $$
BEGIN
    INSERT INTO PLANO (NOME, VALOR_CON, VALOR_INT)
    VALUES (NOME, VALOR_CON, VALOR_INT);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_INTERNA(
    COD_PAC INT,
    COD_PLANO INT,
    CRM INT,
    NUMERO INT,
	MOTIVO TEXT,
    DT_INTERNA DATE
) RETURNS VOID AS $$
BEGIN
    INSERT INTO INTERNACAO (COD_PAC, COD_PLANO, CRM, NUMERO, MOTIVO, DT_INTERNA)
    VALUES (COD_PAC, COD_PLANO, CRM, NUMERO, MOTIVO, DT_INTERNA);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_SERVICO(
    NOME TEXT,
    DESCRICAO TEXT,
    PRECO NUMERIC
) RETURNS VOID AS $$
BEGIN
    INSERT INTO SERVICO (NOME, DESCRICAO, PRECO)
    VALUES (NOME, DESCRICAO, PRECO);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_MEDICO(
    CRM INT,
    NOME TEXT,
    CPF TEXT,
    CONTATO TEXT,
    ENDERECO TEXT
) RETURNS VOID AS $$
BEGIN
    INSERT INTO MEDICO (CRM, NOME, CPF, CONTATO, ENDERECO)
    VALUES (CRM, NOME, CPF, CONTATO, ENDERECO);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_SUPERVISAO(
    COD_SUPERVISOR INT,
    COD_SUPERVISIONA INT
) RETURNS VOID AS $$
BEGIN
    INSERT INTO SUPERVISAO (COD_SUPERVISOR, COD_SUPERVISIONA)
    VALUES (COD_SUPERVISOR, COD_SUPERVISIONA);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_PM(
    COD_MED INT,
    COD_PLANO INT,
    PRECO NUMERIC
) RETURNS VOID AS $$
BEGIN
    INSERT INTO PM (COD_MED, COD_PLANO, PRECO)
    VALUES (COD_MED, COD_PLANO, PRECO);
END;
$$ LANGUAGE PLPGSQL;

CREATE OR REPLACE FUNCTION INSERIR_APARTAMENTO(
    NUMERO INT,
    LOCALIZACAO TEXT
) RETURNS VOID AS $$
BEGIN
    INSERT INTO APARTAMENTO (NUMERO, LOCALIZACAO)
    VALUES (NUMERO, LOCALIZACAO);
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION INSERIR_CARGO(
    NOME TEXT,
    SALARIO NUMERIC
) RETURNS VOID AS $$
BEGIN
    INSERT INTO CARGO (NOME, SALARIO)
    VALUES (NOME, SALARIO);
END;
$$ LANGUAGE PLPGSQL;











