-- ATENDENTE

CREATE ROLE ATENDENTE WITH 
LOGIN
NOSUPERUSER
NOCREATEDB
NOCREATEROLE
NOINHERIT
PASSWORD 'atendente123';

GRANT EXECUTE ON FUNCTION GERAR_FATURA_INTERNA(INT), INSERIR_LINHA(TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT), 
GERAR_FATURA_CONSULTA(INT) TO ATENDENTE;

GRANT INSERT, UPDATE, SELECT ON PACIENTE, CONSULTA, INTERNACAO, PROCEDIMENTO TO ATENDENTE;
GRANT SELECT ON PLANO, ITEM_MED, PM TO ATENDENTE;

GRANT USAGE, SELECT ON SEQUENCE internacao_cod_interna_seq, paciente_cod_pac_seq, 
procedimento_cod_proced_seq, consulta_cod_consul_seq, plano_cod_plano_seq TO ATENDENTE;


SET SESSION AUTHORIZATION ATENDENTE;
SELECT INSERIR_LINHA('PACIENTE', '12343248901', 'Maria João', '123412281', 'Rua E');
--SELECT GERAR_FATURA_INTERNA(1);
--SELECT INSERIR_LINHA('APARTAMENTO', '102', 'Bloco B');
RESET SESSION AUTHORIZATION;


-- MEDICO

CREATE ROLE MEDICO WITH 
LOGIN
NOSUPERUSER
NOCREATEDB
NOCREATEROLE
NOINHERIT
PASSWORD 'medico123';

GRANT EXECUTE ON FUNCTION LIBERAR_ALTA(INT), ATUALIZAR_STATUS_CONSULTA(INT, VARCHAR) TO MEDICO;
GRANT UPDATE, SELECT ON INTERNACAO, CONSULTA TO MEDICO;
GRANT USAGE, SELECT ON SEQUENCE internacao_cod_interna_seq, consulta_cod_consul_seq TO MEDICO;

SET SESSION AUTHORIZATION MEDICO;
SELECT INSERIR_LINHA('MEDICO', '123', 'DAVID', '329812398', '23901329', 'RUA JOÃO');
SELECT GERAR_FATURA_INTERNA(1);
-- SELECT LIBERAR_ALTA(1);
RESET SESSION AUTHORIZATION;

CREATE ROLE ADMINISTRADOR WITH 
LOGIN
SUPERUSER
NOCREATEDB
CREATEROLE
NOINHERIT
PASSWORD 'admin';

SET SESSION AUTHORIZATION ADMINISTRADOR;
SELECT INSERIR_LINHA('PACIENTE', '1234321111', 'Maria José', '1231232281', 'Rua F');
SELECT GERAR_FATURA_INTERNA(1);
-- SELECT LIBERAR_ALTA(1);
RESET SESSION AUTHORIZATION;

GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ADMINISTRADOR;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO ADMINISTRADOR;