CREATE TABLE HOSPEDE 
(COD_HOSP INT NOT NULL PRIMARY KEY,
NOME VARCHAR(20) NOT NULL,
DT_NASC DATE);

CREATE TABLE ATENDENTE
(COD_ATEND INT NOT NULL PRIMARY KEY,
NOME VARCHAR(40) NOT NULL,
DT_NASC DATE);

CREATE TABLE CATEGORIA
(COD_CAT INT NOT NULL PRIMARY KEY,
NOME VARCHAR(50) NOT NULL, 
VALOR_DIA FLOAT NOT NULL);

CREATE TABLE APTO
(NUM INT NOT NULL PRIMARY KEY,
STATUS CHAR(1) NOT NULL,
COD_CAT INT NULL REFERENCES CATEGORIA(COD_CAT));

CREATE TABLE HOSPEDAGEM
(COD_HOSPEDA INT NOT NULL PRIMARY KEY,
COD_HOSP INT NOT NULL REFERENCES HOSPEDE(COD_HOSP),
NUM INT NOT NULL REFERENCES APTO(NUM),
COD_ATEND INT NOT NULL REFERENCES ATENDENTE(COD_ATEND),
DT_ENT DATE NOT NULL,
DT_SAI DATE);

DROP TABLE HOSPEDAGEM

INSERT INTO tabela VALUES ();
INSERT INTO HOSPEDE VALUES (1,'JOÃO','2000-11-17'),(2,'MARIA','2004-09-09'),
(3,'JOSÉ','2005-10-09');

INSERT INTO CATEGORIA VALUES(1,'LUXO',700),(2,'SIMPLES',300);

INSERT INTO APTO VALUES (201,'D',1)
INSERT INTO APTO VALUES (302,'D',2)

DELETE FROM tabela WHERE condição(ões);
DELETE FROM APTO WHERE NUM=201;
DELETE FROM CATEGORIA WHERE COD_CAT=1;

UPDATE tabela
SET atributo=novo_valor
WHERE condição(ões);

UPDATE HOSPEDE 
SET NOME = 'JOSÉ MARIA'
WHERE NOME='JOSÉ' OR NOME='MARIA';


SELECT atributo(s) FROM tabela(s) WHERE condição(ões)

SELECT NOME FROM HOSPEDE WHERE COD_HOSP=2 OR COD_HOSP=1;

SELECT NOME FROM HOSPEDE WHERE COD_HOSP=2 AND COD_HOSP=1;

SELECT * FROM APTO

SELECT NOME FROM HOSPEDE WHERE DT_NASC>='2004-01-01' AND
DT_NASC<='2004-12-31'

SELECT NOME FROM HOSPEDE WHERE 
DT_NASC BETWEEN '2004-01-01' AND '2004-12-31'

SELECT NOME FROM HOSPEDE WHERE COD_HOSP=1 OR COD_HOSP=3 OR COD_HOSP=7
OR COD_HOSP=22;

SELECT NOME FROM HOSPEDE WHERE COD_HOSP IN (1,3,7,22);

SELECT COD_HOSP, NOME FROM HOSPEDE WHERE NOME ILIKE '%s%' OR 
NOME ILIKE '%M%'

SELECT COD_HOSP, NOME FROM HOSPEDE WHERE NOME NOT ILIKE '%s%'


--OBTER O NÚMERO DOS APARTAMENTOS QUE SÃO DA CATEGORIA LUXO.
SELECT NUM FROM APTO WHERE COD_CAT IN (SELECT COD_CAT FROM CATEGORIA
									 WHERE NOME='LUXO');

--OBTER O NOME DOS HÓSPEDES QUE SE HOSPEDARAM EM APARTAMENTOS
--DE CATEGORIA DE CÓDIGO 2.
SELECT NOME FROM HOSPEDE WHERE COD_HOSP IN 
(SELECT COD_HOSP FROM HOSPEDAGEM WHERE NUM IN (SELECT NUM FROM APTO WHERE
											  COD_CAT=2));


/*SGSDFG
DFHDTHDT
DHDT
*/


%
_




--FUNÇÕES AGREGADAS
MIN() --MENOR VALOR
MAX() --MAIOR VALOR
COUNT(*) --CONTAR 
SUM() --SOMAR
AVG() --FAZER MÉDIA 

SELECT * FROM HOSPEDE
UPDATE HOSPEDE SET DT_NASC='2000-10-09' WHERE COD_HOSP=3

SELECT MIN(COD_HOSP) FROM HOSPEDE 
WHERE DT_NASC BETWEEN '2000-01-01' AND '2000-12-31'

-- QUAL O NOME DO HÓSPDE DE MAIOR CÓDIGO
SELECT NOME FROM HOSPEDE WHERE 
DT_NASC IN (SELECT MAX(DT_NASC) FROM HOSPEDE)

SELECT * FROM HOSPEDE

SELECT MIN(NOME) FROM HOSPEDE

INSERT INTO HOSPEDE VALUES(4,'MARIA','2000-04-04')

--OBTER O NOME DOS HÓSPEDES QUE SE HOSPEDARAM NA DATA '2023-11-28'
SELECT NOME FROM HOSPEDE WHERE COD_HOSP IN (SELECT COD_HOSP FROM 
										  HOSPEDAGEM WHERE 
										   DT_ENT='2023-11-28')

--OBTER O NOME DOS HÓSPEDES QUE SE HOSPEDARAM EM APARTAMENTOS DA
--CATEGORIA DE CÓDIGO 2
SELECT NOME FROM HOSPEDE WHERE 
COD_HOSP IN (SELECT COD_HOSP FROM HOSPEDAGEM WHERE 
NUM IN (SELECT NUM FROM APTO WHERE COD_CAT=2))

--OBTER O NOME DOS HÓSPEDES QUE SE HOSPEDARAM EM APARTAMENTOS DA
--CATEGORIA CUJO NOME POSSUI A PALAVRA LUXO
SELECT NOME FROM HOSPEDE WHERE 
COD_HOSP IN (SELECT COD_HOSP FROM HOSPEDAGEM WHERE 
NUM IN (SELECT NUM FROM APTO WHERE
COD_CAT IN (SELECT COD_CAT FROM CATEGORIA WHERE NOME ILIKE '%LUXO%')))

--OBTER O NOME DOS HÓSPEDES QUE SE HOSPEDARAM EM APARTAMENTOS DA
--CATEGORIA DE CÓDIGO 2 OU FORAM ATENDIDOS PELO ATENDENTE JOSÉ
SELECT NOME FROM HOSPEDE WHERE COD_HOSP IN
(SELECT COD_HOSP FROM HOSPEDAGEM WHERE NUM IN
(SELECT NUM FROM APTO WHERE COD_CAT=2) OR COD_ATEND IN
(SELECT COD_ATEND FROM ATENDENTE WHERE NOME='JOSÉ'))

--OBTER O NOME DOS HÓSPEDES QUE SE HOSPEDARAM EM APARTAMENTOS
--DA CATEGORIA MAIS CARA
SELECT NOME FROM HOSPEDE WHERE COD_HOSP IN
(SELECT COD_HOSP FROM HOSPEDAGEM WHERE NUM IN
(SELECT NUM FROM APTO WHERE COD_CAT IN
(SELECT COD_CAT FROM CATEGORIA WHERE VALOR_DIA IN
(SELECT MAX(VALOR_DIA) FROM CATEGORIA))))


--OBTER O NOME DO HÓSPEDE MAIS VELHO QUE FOI ATENDIDO PELO ATENDENTE MAIS JOVEM
SELECT NOME FROM HOSPEDE WHERE DT_NASC IN
(SELECT MIN(DT_NASC) FROM HOSPEDE WHERE COD_HOSP IN
(SELECT COD_HOSP FROM HOSPEDAGEM WHERE COD_ATEND IN
(SELECT COD_ATEND FROM ATENDENTE WHERE DT_NASC IN
(SELECT MAX(DT_NASC) FROM ATENDENTE))))


SELECT * FROM HOSPEDE

ALTER TABLE HOSPEDE
ADD COLUMN NACIONALIDADE VARCHAR(50) NOT NULL DEFAULT 'NÃO INFORMADO'

UPDATE 


INSERT INTO HOSPEDE(NOME,COD_HOSP,DT_NASC,NACIONALIDADE) VALUES (6,'MARIAZINHA','2000-03-03')

ALTER TABLE HOSPEDE
DROP COLUMN NACIONALIDADE







