@startuml Biblioteca
!theme materia-outline

    class Biblioteca {
        
    }

    class Funcionario {
        nome : string
        matFunc : Integer
    }

    class Publicacao {
        codPublcacao:
        titulo:
        anoPublica: 
    }

    class Exemplar {

    }

    class Revista {
        dtPublicacao: 
    }

    class Livro {
        codISBN:
    }

    class Jornal {
        tituloMateria:
        nomeJornal:
        cidadePublcacao:
        dTpublicacao:
    }

    class Emprestimo {
    }

    class Reserva {

    }

    Biblioteca "1" -- "1..*" Funcionario
    Biblioteca "1..*" -- "1..*" Publicacao
    Funcionario "1" -- "0..*" Reserva
    Funcionario "1" -- "1..*" Emprestimo
    Exemplar -- Publicacao
    Emprestimo --o Exemplar
    Reserva --o Publicacao
    Publicacao <|-- Jornal
    Publicacao <|-- Livro
    Publicacao <|-- Revista
    

@enduml
